INSERT INTO users (name, email, password) 
VALUES ('Allen Morales', 'elizabethhood@live.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Dollie Stephens', 'emmamorton@ymail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Ray Mendez', 'clarawyatt@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) 
VALUES (1, 'Exclaimed zero', 'Know kept twenty cow greater voice per palace will let favorite stranger fox forth swimming donkey at pair imagine cup primitive getting believed look constantly fourth me shout hang modern yes command current silent division future put choose hat concerned research crowd horn pressure crew run speed themselves wind interest molecular real flow yellow becoming wise find return plates does diagram nature label occur consist judge brave forget some company sleep pool fill caught break breath chicken recent language skill nervous fifth steady lose part rough occur should depth repeat state state third officer prove hunt year town aid chamber plenty at root mail lungs usual caught before forget burst struck mighty purple has jar cowboy noun contain continent laid thing merely coast eye were willing me rate engine labor loud event conversation piano examine necessary listen major today adult separate double appearance rope will together stock chest quickly center was tone range carried tank figure halfway from particles dug ball tower this primitive outer deal three dozen heading firm sometime shall difference tight men worker lost stared equal however search whale under under were asleep element nearer badly spend sum brother best report sit tail money thumb chemical where favorite bound leg bee putting later choose case direction book stream riding are joined war blow model therefore powerful coming essential grandfather rubber company shade south sink love struck difference means long want just faster vast one molecular came attempt maybe stomach roar driving cup completely pony gone her done inside cup grass purple scene even compound sheep my central successful row police inch boy improve pencil east nest mouse owner feel fine everywhere shine globe once hot somewhere paid serious ranch fun gulf way grabbed roar negative wrote hall regular terrible color middle understanding sudden brought told original tropical', 851, 'https://images.pexels.com/photos/259957/pexels-photo-259957.jpeg', 'https://images.pexels.com/photos/259957/pexels-photo-259957.jpeg?auto=compress&cs=tinysrgb&h=350', 19658, 1, 6, 0, true, 'Ontario', 'Sarnia', 'Canada', '1196 Homig Turnpike', '59784'),
(2, 'Daily every', 'Sick foot brain express truth sure written exclaimed entire ability next treated store coast tail kept coast sheet symbol zulu gradually season southern oxygen than appropriate title see work making draw plates canal contrast whom page five rocky evidence operation active steam yesterday hurt earlier movement branch dig some light peace parent fighting driving memory variety final replace catch monkey born shape brush brown fewer wore duty show direct mood quarter spread opportunity salmon paint cool school blew mail toy about thrown pond bottom burst gasoline taught driver great tropical is brother human hurried truck top tin nodded skin breathe world fat than dust origin slow dust tired harder summer point underline sides equal birthday dig brass around me lungs to tent word definition fair equator grow seems duck feathers examine song ten direction stage tax happily eye using pitch forward memory mad captured into low advice officer judge he onto breakfast verb attached gave discovery managed ran faster ago enemy train guard park welcome everybody excited skill date recall hot nervous examine first pilot house select clothes alone policeman play join steel weak like first pony danger aware of prevent steel further throat has leaving ordinary operation got gain week ill ill diameter composition milk select seed there sheep year spin some memory mysterious sides trap walk composed possible lungs good peace measure gradually rise service frozen inch dog love apart became oldest song customs number bottom outline office married plural reason structure stock someone worse must creature ready gently fireplace us court mill vessels very grade gradually simplest escape harbor excellent community control tired him create suggest pine sun principal start worker organized began food choice until subject putting tube fair spider typical eat known total difficulty forget expression shore develop important condition adjective universe production shade train', 103, 'https://images.pexels.com/photos/2088258/table-dining-room-chair-dining-area-2088258.jpeg', 'https://images.pexels.com/photos/2088258/table-dining-room-chair-dining-area-2088258.jpeg?auto=compress&cs=tinysrgb&h=350', 2438, 8, 2, 1, true, 'Prince Edward Island', 'Charlottetown', 'Canada', '1716 Misih Highway', '48752'),
(3, 'Prepare if', 'Angry pair does flame factory night sum party trip tomorrow none friend rain quickly generally grew bell row my stairs turn sang possibly having badly over bit inside six industry lonely scientific use he only as long feel instrument worth struggle almost material pilot good roar raw past chief describe join parts welcome feed figure trip settlers partly egg happily have forth bad percent join tobacco writing harder dream series shaking nuts wrong trap actual electric limited join deal hand tape know serve divide sky everyone we snow save mill engineer declared tea proper again earlier strange away aid yet total capital regular pride dream tape example hidden both sense possible earn increase environment area join sand pleasant made hungry throat safety such fighting fruit molecular event thread saw fall clay people stranger chose though citizen state value wild pitch want flower calm nervous silk lovely chosen transportation practice change what occur symbol else thank rose drew central needs proper great twice family shore sink pile clothes character song pocket public unusual chemical canal jar dug together track easily exist organization thou valley ants official accept wide shorter bottle nearby population highest seldom middle weigh anything strength allow guess wore pig cut price special neighborhood nature southern worry properly slow garage religious breath fix dog window human due hurt replied knife gather shop series see sunlight first girl western word vowel look shallow free shout specific alike bell positive deer donkey won union tobacco supper fence discuss seldom possible women science chamber perfect swam principal only elephant tone zero hold instance claws upper hide when anywhere told island aside brown town planet climate layers tribe elephant acres like aware nose jump advice extra thin first flight door stared machinery poetry season climb hand wheat wheat rising fog being tower brick', 184, 'https://images.pexels.com/photos/1027512/pexels-photo-1027512.jpeg', 'https://images.pexels.com/photos/1027512/pexels-photo-1027512.jpeg?auto=compress&cs=tinysrgb&h=350', 21137, 4, 7, 2, true, 'Ontario', 'Orillia', 'Canada', '1492 Ufimo Junction', '47597');
INSERT INTO reservations ( guest_id, property_id, start_date, end_date)
VALUES (1, 147, 94, '2022-07-16', '2022-08-09'),
(2, 2, '2022-11-18', '2022-12-10'),
(3, 3, '2016-04-10', '2016-04-26');
INSERT INTO property_reviews ( guest_id, property_id, reservation_id, rating, message) 
VALUES (1, 798, 1018499, 5, 'Loj ce jig so ker no lu okgeeb asobir ridiwheg debi mo ne hun.'),
(2, 31, 1015537, 5, 'Babikil fagut iju za jemuzewu giruna ugke tuh ewoemli boc fag tomim umo.'),
(3, 347, 1017570, 5, 'Waoj nip mak gen foh az ut woc ub ojo hewosa karsivin kusap jacikbit.');